### ISSUE TITLE
Add EmberJS support as an option to Discourse Sentry

### ISSUE THREAD

**Issue by unixneo** [debtcollective/discourse-sentry#2]
**What:**

Add EmberJS support as an option to Discourse Sentry

**Why:**

 EmberJS is a core part of Discourse and Sentry supports EmberJS

**How:**

https://docs.sentry.io/platforms/javascript/guides/ember/

**Comment by orlando** [comment]
Hey @unixneo,

Thanks for opening this issue. I'll be more than happy to merge a PR for this.
